### ISSUE TITLE
async_hooks.executionAsyncId is not a function

### ISSUE THREAD

**Issue by jimsimon** [Jeff-Lewis/cls-hooked#13]
I'm getting the following error when trying to use cls-hooked with Express 4 and Sequelize 4 on node 8.4.0:

```
TypeError: async_hooks.executionAsyncId is not a function
    at AsyncHook.init (/usr/src/app/node_modules/cls-hooked/context.js:291:32)
    at init (async_hooks.js:444:43)
    at emitInitS (async_hooks.js:314:3)
    at setupInit (internal/process/next_tick.js:225:7)
    at process.nextTick (internal/process/next_tick.js:247:5)
    at onwrite (_stream_writable.js:419:15)
    at Socket._writeGeneric (net.js:770:5)
    at Socket._write (net.js:780:8)
    at doWrite (_stream_writable.js:371:12)
    at writeOrBuffer (_stream_writable.js:357:5)
```

I have an express middleware that looks like this:
```js
const { createNamespace } = require('cls-hooked')
const shardingNamespace = createNamespace('sharding')

// Patch bluebird to ensure cls context isn't lost
const clsBluebird = require('cls-bluebird')

const Promise = require('bluebird')
clsBluebird(shardingNamespace, Promise)

const sequelizePromise = require('sequelize/lib/promise')
clsBluebird(shardingNamespace, sequelizePromise)

module.exports = function (req, res, next) {
  shardingNamespace.bindEmitter(req)
  shardingNamespace.bindEmitter(res)

  shardingNamespace.run(function () {
    shardingNamespace.set('shard', 'default')
    next()
  })
}
```

One thing to note is that Sequelize creates its own instance of bluebird via `const Promise = require('bluebird').getNewLibraryCopy();`.  I'm wondering if that's causing the issue.  Putting a `console.log(async_hooks.executionAsyncId)` before context.js line 291 shows that most of the time it's a valid function, but occasionally it's undefined.

Any idea what might be causing this?

**Comment by jimsimon** [comment]
Not sure what I changed, but I'm getting a slightly different stack trace now:
```
TypeError: async_hooks.executionAsyncId is not a function
    at AsyncHook.init (/usr/src/app/node_modules/cls-hooked/context.js:291:32)
    at Promise.init (async_hooks.js:444:43)
    at Promise (<anonymous>)
    at Object.getNativePromise (/usr/src/app/node_modules/bluebird/js/release/util.js:323:27)
    at Object.<anonymous> (/usr/src/app/node_modules/bluebird/js/release/schedule.js:7:26)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by Beans0063** [comment]
I was experiencing this same issue and it resolved by upgrading to 8.6.0

**Comment by kweiberth** [comment]
the solution from @Beans0063 also worked for me. I was using node 8.1.2, and upgrading to 8.8.1 solved this issue for me

**Comment by jimsimon** [comment]
Yep, upgrading fixed it for me as well.  Thanks!

**Comment by SupernaviX** [comment]
If this doesn't work with older versions of node, could this library still use the shim on node<8.6.0 (or the lowest compatible version)?

**Comment by benderTheCrime** [comment]
@SupernaviX looks like it just checks a static NodeJS version. I'm going to fork and open a PR.

**Comment by benderTheCrime** [comment]
Ok, so this is actually non-trivial. It's the writing between the lines that's important here:

https://www.npmjs.com/package/cls-hooked#when-running-nodejs-version--8-this-module-uses-asyncwrap-which-is-an-unsupported-nodejs-api-so-please-consider-the-risk-before-using-it

> When running Nodejs version >= 8.2.1, this module uses the newer async_hooks API which is considered Experimental by Nodejs.

This seems fine if I set the check to `semver.gte(process.versions.node, '8.2.0')` even, NodeJS@8.2.1 is well working as indicated by the README.md. This is also true of 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, and 8.9.

https://www.npmjs.com/package/cls-hooked#when-running-nodejs-version--8-this-module-uses-asyncwrap-which-is-an-unsupported-nodejs-api-so-please-consider-the-risk-before-using-it

> When running Nodejs version < 8, this module uses AsyncWrap which is an unsupported Nodejs API, so please consider the risk before using it.

This is also true. I tested with 6.10, 7.3, and they both worked well.

8.1.4 on the other hand does not work well, with either the legacy or the new APIs. 

Incidentally, the async_hooks module does exist in NodeJS@8.1.4, it is just missing the `executionAsyncId` method. This I believe can be replaced with the `currentId` property. Doing so shows 3-4 failing tests, which is not bad.

@Jeff-Lewis is this something we can consider doing with a switch for the `getCurrentId` function?
Something along the lines of:

```javascript
const getCurrentId = semver.gte(process.versions.node, '8.2.0') ? async_hooks.getExecutionId : () => async_hooks.currentId;
```
