### ISSUE TITLE
Difference with async-local-storage

### ISSUE THREAD

**Issue by blacksonic** [Jeff-Lewis/cls-hooked#15]
Can someone explain what is the difference between this library compared to https://github.com/vicanso/async-local-storage ? That library seems super simple.

I checked other solutions as we are having issues with destroying the namespace.
Is destroying the namespace necessary on every request?
Here is our middleware: 
```
return async function(ctx, next) {
      const namespace = continuationLocalStorage.createNamespace('session');

      try{
        await new Promise(namespace.bind(function(resolve, reject) {
          namespace.set('request_id', ctx.request.header['x-request-id']);

          next().then(resolve).catch(reject);
        }));
      } catch(error) {
        throw error;
      } finally {
        continuationLocalStorage.destroyNamespace('session');
      }
    };
```

**Comment by carlisliu** [comment]
Basically the same.  this module supports node 'Async Hooks' api compared with [node-continuation-local-storage](https://github.com/othiym23/node-continuation-local-storage), so there is no need to wrap every asynchronous function like node-continuation-local-storage does.

**Comment by Jeff-Lewis** [comment]
At first glance and without comparing in detail the async_hook event state management of [async-local-storage](https://github.com/vicanso/async-local-storage), I assume for the latest node 8 versions, it and [cls-hooked](https://github.com/Jeff-Lewis/cls-hooked) would behave the same. 

One clear difference is [cls-hooked](https://github.com/Jeff-Lewis/cls-hooked) provides backward compatibility with node 6 & 7 using AsyncWrap when running in those versions. It also provides the same interface as [node-continuation-local-storage](https://github.com/othiym23/node-continuation-local-storage) to make it easier for devs to try.

As for destroying namespaces, its not required but I guess it depends how you're using it. I'm not sure what framework your middleware example is from, but usually namespaces are created sparingly, such as a "sessions" namespace, while contexts are created on that namespace for things like requests and sessions.

Btw, I love the simple and elegant code of `async-local-storage`... it makes me want to rewrite `cls-hooked`... when days start to have 36 hours in them...

**Comment by blacksonic** [comment]
@Jeff-Lewis It is a Koa middleware, and wanted to make request id available in subsequent calls.
How can i refactor it to use one namespace, but the context remains?

**Comment by Jeff-Lewis** [comment]
Take a look at these for examples:
https://github.com/othiym23/cls-middleware
https://github.com/madbence/koa-continuation-local-storage
https://github.com/clakech/cls-hooked-sample

Just create the namespace outside of the middleware handler function. I see most apps create the namespace once when initializing the server app.

**Comment by Jeff-Lewis** [comment]
@blacksonic Closing for now. Let me know if you have any issues.
