### ISSUE TITLE
[Question] Unit test an Express middleware using cls-hooked

### ISSUE THREAD

**Issue by xballoy** [Jeff-Lewis/cls-hooked#17]
Hello,

I'm trying to write a unit test to check if the value I set is well setted in my middleware.

A simplified version (the namespace 'mynamespace' is already created) of my middleware is:
```
module.exports = (req, res, next) => {
  ns.bindEmitter(req);
  ns.bindEmitter(res);

  ns.run(() => {
    const correlationId = uuidV4();
    getNamespace('mynamespace').set('correlationId', correlationId);
    next();
  });
};
```

My failing test is:
```
it.only('should set a correlationId in the uuid format in the request and the response', done => {
    const req = new Emitter();
    const res = new Emitter();
    const next = sinon.stub();

    correlationIdMiddleware(ns)(req, res, next);

    ns.run(() => {
        const correlationId = ns.get('correlationId');
        correlationId.should.satisfy(isUUID.v4);
        done();
    });
  });
```
It says that `correlationId` is `undefined`. My guess is that `correlationId` doesn't exist anymore when I check it in my unit test.

When I run my application I can see my middleware working.

Any idea? Thanks!

**Comment by Jeff-Lewis** [comment]
It's hard to say without knowing what `correlationIdMiddleware` does but it looks like the context only lives during the execution of `correlationIdMiddleware`.

Take a look at [cls-middleware](https://github.com/othiym23/cls-middleware) and [cls-hooked-sample](https://github.com/clakech/cls-hooked-sample) to get an idea of the context's lifecycle in middleware and ways to test it.

**Comment by xballoy** [comment]
Thanks. I'll have a look!

**Comment by maldimirov** [comment]
@xballoy did you resolve the issue? What is the solution?

**Comment by xballoy** [comment]
I never managed to make it works, sorry...

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by krotscheck** [comment]
In case anyone runs into this, this works for me:

```
import { ns } from '../auth/request-context';

describe('a test', () => {
     let context;

     beforeEach(() => {
         context = ns.createContext();
         ns.enter(context);
    });

    it('should store and retrieve a value', () => {
         ns.set('key', 'value');
         const response = ns.get('key');
         response.should.equal('value');
    });

    afterEach(() => {
        ns.exit(context);
    });
});

```
