### ISSUE TITLE
Not working in node v10.0.0

### ISSUE THREAD

**Issue by josuerios** [Jeff-Lewis/cls-hooked#24]
Test fails in node v10.0.0

Repro steps 
1. Install nodejs v10.0.0
2. Run tests 

context is being missed so tests breaks.

**Comment by mcasimir** [comment]
can it be related to https://github.com/nodejs/node/commit/1cc6b993b9 ?

**Comment by Jeff-Lewis** [comment]
It looks like v10 needs a little review with regards to async_hooks. See [Different async_hooks behavior in Node 10 #20274](https://github.com/nodejs/node/issues/20274)

**Comment by Conduitry** [comment]
Ah, after I ran into that Node 10 issue I had intended to see whether that also affected this library's functionality but I guess now I don't have to :(

**Comment by JustGreg** [comment]
i can confirm that cls-hooked is working in node 10.4
https://github.com/nodejs/node/issues/20274#issuecomment-395200647

**Comment by Jeff-Lewis** [comment]
Thanks @JustGreg

**Comment by Jeff-Lewis** [comment]
Todo: Add warning or update npm node version requirements
